server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: authorization
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  security:
    oauth2:
      jwt:
        signingKey: ${JWT_KEY:123456}
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/platform

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    com.wind.auth.authorization: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'
